# plomlompom's bashrc for non-login shells

# Fancy colors for ls.
alias ls="ls --color=auto"

# Use vim as default editor for anything.
export VISUAL=vim
export EDITOR=$VISUAL

# Wrapper for weechat to force local config file on it anew on each run.
alias weechat="~/config/bin/weechat-wrapper.sh"

# Blue prompt with time.
PS1="\[\e[1;34m\][\\t \\u@\\h \\w]$\[\e[m\] "
PS2="\[\e[1;34m\]>\[\e[m\] "
PS3="\[\e[1;34m\]>\[\e[m\] "
PS4="\[\e[1;34m\]+\[\e[m\] "
