# plomlompom's bashrc for non-login shells (root)

# Fancy colors for ls.
alias ls="ls --color=auto"

# Use vim as default editor for anything.
export VISUAL=vim
export EDITOR=$VISUAL

# Red prompt with time.
PS1="\[\e[1;31m\][\\t \\u@\\h \\w]$\[\e[m\] "
PS2="\[\e[1;31m\]>\[\e[m\] "
PS3="\[\e[1;31m\]>\[\e[m\] "
PS4="\[\e[1;31m\]+\[\e[m\] "
