# Bash as a non-login shell in non-POSIX-mode does not read in the startup
# script at the path in $ENV. This forces it to still read in the ~/.shinit
# startup script for non-login shells.

. ~/.shinit

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
