# X init configuration

# Set keymap.
setxkbmap de

# Read in X configuration.
xrdb -merge ~/.Xresources
xrdb -merge ~/.Xresources-local

# Redshift to Berlin, Germany.
redshift -rl 53:13 &

# Enforce QWERTZ.
setxkbmap de

# Launch window manager.
i3
